// src/app/components/login/login.component.ts
import {Component, OnInit} from '@angular/core';
import {NearService} from "../../services/near.service";
import {environment} from "../../../environments/environment";

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  public accountId: any;

  constructor(public nearService: NearService) {
  }

  ngOnInit(): void {
    this.accountId = this.nearService.wallet.getAccountId();
  }

  signIn() {
    this.nearService.wallet.requestSignIn(environment.CONTRACT_ID);
  }

  signOut() {
    this.nearService.wallet.signOut();
    localStorage.removeItem(`near-api-js:keystore:${this.accountId}:testnet`);
    this.accountId = this.nearService.wallet.getAccountId()
  }
}

<div class="px-5 flex w-1/2 justify-end items-center">
  <div *ngIf="accountId; else elseBlock">
    <div class="flex items-center justify-between">
      <div class="flex items-center justify-center h-12 w-36 rounded-md bg-indigo-500 text-white mx-2">
        <hero-icon name="user" hostDisplay="inlineBlock" type="outline" class="w-6 h-6 text-black-500"></hero-icon>
        <h4 class="mr-2">{{accountId}}</h4>
      </div>
      <!-- <div class="flex items-center justify-center h-12 w-32 rounded-md bg-indigo-500 text-white mx-2">
        <CashIcon  class="w-6 h-6 text-black-500 mx-2"/>
        <span class="mx-1 text-white-500 font-bold sm:text-sm ">
                 {{balance}} Ⓝ
          </span>
      </div> -->
      <div class="flex items-center justify-center h-12 w-12 rounded-md bg-indigo-500 text-white mx-2">
        <hero-icon name="logout" hostDisplay="inlineBlock" type="outline" class="w-6 h-6 text-black-500"
                   (click)="signOut()"></hero-icon>
      </div>
    </div>
  </div>
  <ng-template #elseBlock>
    <button (click)="signIn()"
            class="self-end rounded-3xl  py-3 px-10 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
      Login
    </button>
  </ng-template>
</div>

// src/components/Login.vue
<template>
  <div class="px-5 flex w-1/2 justify-end items-center">
      <div v-if="accountId">
          <div class="flex items-center justify-between">
            <div class="flex items-center justify-center h-12 w-36 rounded-md bg-indigo-500 text-white mx-2">
              <UserIcon  class="w-6 h-6 text-black-500"/>
              <h4 class="mr-2">{{accountId}}</h4>
            </div>
            <!-- <div class="flex items-center justify-center h-12 w-32 rounded-md bg-indigo-500 text-white mx-2">
              <CashIcon  class="w-6 h-6 text-black-500 mx-2"/>
              <span class="mx-1 text-white-500 font-bold sm:text-sm ">
                       {{balance}} Ⓝ
                </span>
            </div> -->
             <div class="flex items-center justify-center h-12 w-12 rounded-md bg-indigo-500 text-white mx-2">
                 <LogoutIcon class="w-6 h-6 text-black-500" @click="signOut"/>
            </div>
          </div>      
      </div>
      <button v-else @click="signIn" class="self-end rounded-3xl  py-3 px-10 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Login
      </button>
    </div>
</template>

<script>
import { UserIcon, LogoutIcon} from '@heroicons/vue/outline'
import { useWallet } from '@/composables/near.js'
export default {
    components: {
        UserIcon,
        LogoutIcon
    },
    setup() {
        const { accountId, signIn, signOut } = useWallet();
        return {
            accountId,
            signIn,
            signOut
        }
    }
}
</script>
